name: Update major version tag

on:
  release:
    types:
      - published

jobs:
  tag:
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: kotaoue/major-tag-floater@baeaf6ba381aa4b4dbd6e2675de5e648e7dc9ff2 # v1
