name: Update major version tag

on:
  release:
    types:
      - published

jobs:
  tag:
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: kotaoue/major-tag-floater@baeaf6ba381aa4b4dbd6e2675de5e648e7dc9ff2 # v1
