name: Update major version tag

on:
  release:
    types:
      - published

jobs:
  tag:
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: kotaoue/major-tag-floater@baeaf6ba381aa4b4dbd6e2675de5e648e7dc9ff2 # v1
